// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFblOBBUqVB4HxA0WN9NrWIo4hUsLmkKI',
    appId: '1:622570988215:web:ae2e76a3653f32871c2332',
    messagingSenderId: '622570988215',
    projectId: 'mimamori-app-75fcf',
    authDomain: 'mimamori-app-75fcf.firebaseapp.com',
    storageBucket: 'mimamori-app-75fcf.firebasestorage.app',
    measurementId: 'G-2Y6J1EX0HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9f7CYg-0NoX6BmHIIqPFYnoWtMC6Oc-o',
    appId: '1:622570988215:android:9eaa423f4d7af14c1c2332',
    messagingSenderId: '622570988215',
    projectId: 'mimamori-app-75fcf',
    storageBucket: 'mimamori-app-75fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz6jYDcwCN2dHbBb_ASsoaXswpMjZk0ZU',
    appId: '1:622570988215:ios:e063ecd0dcd378f91c2332',
    messagingSenderId: '622570988215',
    projectId: 'mimamori-app-75fcf',
    storageBucket: 'mimamori-app-75fcf.firebasestorage.app',
    iosBundleId: 'com.example.mimamoriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz6jYDcwCN2dHbBb_ASsoaXswpMjZk0ZU',
    appId: '1:622570988215:ios:e063ecd0dcd378f91c2332',
    messagingSenderId: '622570988215',
    projectId: 'mimamori-app-75fcf',
    storageBucket: 'mimamori-app-75fcf.firebasestorage.app',
    iosBundleId: 'com.example.mimamoriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFblOBBUqVB4HxA0WN9NrWIo4hUsLmkKI',
    appId: '1:622570988215:web:57a47cbc5da8d4431c2332',
    messagingSenderId: '622570988215',
    projectId: 'mimamori-app-75fcf',
    authDomain: 'mimamori-app-75fcf.firebaseapp.com',
    storageBucket: 'mimamori-app-75fcf.firebasestorage.app',
    measurementId: 'G-DJ8NGGG63N',
  );
}
